---
name: CGI-Application-Server
version: 0.03
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
  - 'Rob Kinyon E<lt>rob.kinyon@iinteractive.comE<gt>'
abstract: A simple HTTP server for developing with CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Application: 0
  Carp: 0.01
  HTTP::Request: 0
  HTTP::Server::Simple: 0.18
  HTTP::Server::Simple::Static: 0.02
  HTTP::Status: 0
  IO::Capture::Stdout: 0
  Scalar::Util: 1.18
build_requires:
  CGI::Application::Plugin::Redirect: 0
  Test::Exception: 0.21
  Test::HTTP::Server::Simple: 0.02
  Test::More: 0.47
  Test::WWW::Mechanize: 1.08
provides:
  CGI::Application::Server:
    file: lib/CGI/Application/Server.pm
    version: 0.03
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
